# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-23 09:45
from __future__ import unicode_literals

import applicants.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='First Name')),
                ('surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('indexNumber', models.CharField(max_length=7, unique=True, validators=[applicants.models.indexValidator], verbose_name='Index')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=15, verbose_name='Telephone')),
                ('gpa', models.DecimalField(decimal_places=4, max_digits=5, validators=[applicants.models.gpaValidator])),
                ('aboutMe', models.TextField(verbose_name='About Me')),
                ('vacancy_A', models.IntegerField(default=0, verbose_name='First Choice')),
                ('vacancy_B', models.IntegerField(default=0, verbose_name='Second Choice')),
                ('vacancy_C', models.IntegerField(default=0, verbose_name='Third Choice')),
                ('appeal_A', models.IntegerField(default=0, verbose_name='First Appeal')),
                ('appeal_B', models.IntegerField(default=0, verbose_name='Second Appeal')),
                ('appeal_C', models.IntegerField(default=0, verbose_name='Third Appeal')),
                ('awarded', models.IntegerField(default=0, verbose_name='Awarded Vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutUs', models.TextField(verbose_name='About')),
                ('address', models.CharField(max_length=250, verbose_name='Company Address')),
                ('companyName', models.CharField(max_length=200, verbose_name='Company')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('loginID', models.CharField(max_length=100, verbose_name='Login ID')),
                ('positions', models.IntegerField(default=0, verbose_name='Vacancies Posted')),
                ('telephone', models.CharField(max_length=11, verbose_name='Telephone')),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai', models.BooleanField(default=False, verbose_name='Artificial Intelligence')),
                ('antenna', models.BooleanField(default=False, verbose_name='Antennas')),
                ('arduino', models.BooleanField(default=False, verbose_name='Arduino')),
                ('automation', models.BooleanField(default=False, verbose_name='Automation')),
                ('biomechanics', models.BooleanField(default=False, verbose_name='Bio Mechanics')),
                ('biomedical', models.BooleanField(default=False, verbose_name='Bio Medical')),
                ('circuits', models.BooleanField(default=False, verbose_name='Circuits')),
                ('fpga', models.BooleanField(default=False, verbose_name='FPGA')),
                ('imageProcessing', models.BooleanField(default=False, verbose_name='Image Processing')),
                ('iot', models.BooleanField(default=False, verbose_name='Internet of Things')),
                ('robotics', models.BooleanField(default=False, verbose_name='Robotics')),
                ('networking', models.BooleanField(default=False, verbose_name='Networking')),
                ('processorDesign', models.BooleanField(default=False, verbose_name='Processor Design')),
                ('programming', models.BooleanField(default=False, verbose_name='Programming')),
                ('telecom', models.BooleanField(default=False, verbose_name='Telecommunication')),
                ('semiconductors', models.BooleanField(default=False, verbose_name='Semi-Conductors')),
                ('signalProcessing', models.BooleanField(default=False, verbose_name='Signal Processing')),
                ('wifi', models.BooleanField(default=False, verbose_name='WiFi Technology')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True, verbose_name='Availability')),
                ('is_awarded', models.BooleanField(default=False, verbose_name='Awarded')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('pub_date', models.DateTimeField(verbose_name='Published Date')),
                ('salary', models.IntegerField(default=0, verbose_name='Salary')),
                ('description', models.TextField(null=True, verbose_name='Job Description')),
                ('sub_description', models.TextField(null=True, verbose_name='More..')),
                ('choice', models.IntegerField(default=0, verbose_name='Choice')),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applicants.Applicant')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applicants.Company')),
                ('preferences', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applicants.Preferences')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='preferences',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applicants.Preferences'),
        ),
    ]
