# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-23 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_applicant_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='is_open',
        ),
    ]
