# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-23 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0004_remove_vacancy_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Availability'),
        ),
    ]
